========= 512 

&& 2.0271387100219727, 0.5540235042572021, 2.5849955081939697


&& 2.006380319595337, 0.5682406425476074, 2.5790793895721436

==========ours 

&& 2.0512235164642334, 0.6281111240386963, 2.6835737228393555


&& 2.0667436122894287, 0.6718957424163818, 2.7429678440093994


&& 2.111086845397949, 0.8990895748138428, 3.0149922370910645


&& 2.410259246826172, 1.5557713508605957, 3.969827175140381


&& 3.443678140640259, 4.026372909545898, 7.473822832107544

========= 1024 

&& 2.0116477012634277, 0.5912554264068604, 2.6211915016174316


&& 2.024613380432129, 0.5965671539306641, 2.6397011280059814

==========ours 

&& 2.0358738899230957, 0.7415299415588379, 2.7959513664245605


&& 2.055312156677246, 0.7979927062988281, 2.867873191833496


&& 2.1119155883789062, 1.0534486770629883, 3.183652400970459


&& 2.368729829788208, 1.7509429454803467, 4.138006210327148


&& 3.0854058265686035, 4.551414251327515, 7.6550984382629395

========= 2048 

&& 2.094446897506714, 0.6885855197906494, 2.8586843013763428


&& 2.0812923908233643, 0.6630682945251465, 2.8241333961486816

==========ours 

&& 2.0876553058624268, 1.066439151763916, 3.2295360565185547


&& 2.0943069458007812, 1.1304781436920166, 3.3002583980560303


&& 2.2121121883392334, 1.578695297241211, 3.866546630859375


&& 2.348440408706665, 2.5871083736419678, 5.011263847351074


&& 3.0620973110198975, 5.637307405471802, 8.774951457977295

========= 3072 

&& 2.2239818572998047, 0.9125092029571533, 3.3062849044799805


&& 2.1528453826904297, 0.8832395076751709, 3.2050678730010986

==========ours 

&& 2.241396903991699, 1.5594990253448486, 3.9699463844299316


&& 2.246018886566162, 1.695162057876587, 4.110272645950317


&& 2.287290334701538, 2.123793840408325, 4.581663370132446


&& 2.4697682857513428, 3.5774102210998535, 6.2168073654174805


&& 3.018044948577881, 7.348318576812744, 10.535877704620361

========= 4096 
Traceback (most recent call last):
  File "/home/yufan/labpytorch/uu/benchmarking/vgg16-ref-no-cp.py", line 223, in <module>
    main()
  File "/home/yufan/labpytorch/uu/benchmarking/vgg16-ref-no-cp.py", line 174, in main
    out_ref = model_ref(input_ref)
  File "/home/yufan/labpytorch/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yufan/labpytorch/uu/benchmarking/vgg16-ref-no-cp.py", line 132, in forward
    out = self.block1(x)
  File "/home/yufan/labpytorch/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yufan/labpytorch/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/yufan/labpytorch/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yufan/labpytorch/torch/nn/modules/activation.py", line 102, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/yufan/labpytorch/torch/nn/functional.py", line 1207, in relu
    result = torch.relu(input)
RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 39.59 GiB total capacity; 37.00 GiB already allocated; 504.19 MiB free; 37.61 GiB reserved in total by PyTorch)

&& 2.315394878387451, 1.0664710998535156, 3.6820571422576904

==========ours 
Traceback (most recent call last):
  File "/home/yufan/labpytorch/uu/benchmarking/vgg16-our.py", line 260, in <module>
    main()
  File "/home/yufan/labpytorch/uu/benchmarking/vgg16-our.py", line 220, in main
    loss.backward()
  File "/home/yufan/labpytorch/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/yufan/labpytorch/torch/autograd/__init__.py", line 146, in backward
    Variable._execution_engine.run_backward(
  File "/home/yufan/labpytorch/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/home/yufan/labpytorch/uu/utils/checkpoint.py", line 120, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "/home/yufan/labpytorch/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yufan/labpytorch/uu/layers/sequential.py", line 8, in forward
    inputs = module(*inputs)
  File "/home/yufan/labpytorch/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yufan/labpytorch/uu/layers/conv2d.py", line 449, in forward
    out = tconv2d(input, self.weight, self.bias, self.stride,
  File "/home/yufan/labpytorch/uu/layers/conv2d.py", line 127, in forward
    out = F.conv2d(input, weight, bias, stride,
RuntimeError: CUDA out of memory. Tried to allocate 518.00 MiB (GPU 0; 39.59 GiB total capacity; 36.60 GiB already allocated; 328.19 MiB free; 37.46 GiB reserved in total by PyTorch)

&& 2.382965087890625, 2.574737548828125, 5.2571916580200195


&& 2.453975200653076, 3.0082039833068848, 5.762270450592041


&& 2.566216230392456, 4.560920715332031, 7.426665544509888


&& 3.1545193195343018, 9.123214483261108, 12.577712297439575

